### ISSUE TITLE
Explicitly state types in IMPORT

### ISSUE THREAD

**Issue by redcatbear** [exasol/oracle-virtual-schema#14]
## Situation

The `IMPORT` command produced by the Oracle Virtual Schema does not enforce types. This means, the ExaLoader picks the types and that in Oracle VS' case leads to numbers being expressed as `VARCHAR`.

## Acceptance Criteria

1. Result types are explicitly set in Oracle VS

**Comment by redcatbear** [comment]
This feature is blocked for `IMPORT FROM ORA` since it requires a core database feature where the core informs the VS adapter about the datatypes it wants to see in the result.
As a workaround used `IMPORT FROM JDBC`.

**Comment by pj-spoelders** [comment]
That is correct. Also see #18
