### ISSUE TITLE
Documentation for IMPORT_DATA_TYPES

### ISSUE THREAD

**Issue by allipatev** [exasol/oracle-virtual-schema#29]
Currently the new parameter IMPORT_DATA_TYPES is explained only in [Virtual Schema Common Module for JDBC-based Data Access](https://github.com/exasol/virtual-schema-common-jdbc/blob/main/README.md#virtual-schema-common-module-for-jdbc-based-data-access)

Of course, it is reasonable, DRY.

However, by now I expected User Guides in particular dialects to contain exhaustive information. It is not the case for this parameter IMPORT_DATA_TYPES. And, honestly, there is very little chance for a user to come up with idea to look at repo "virtual-schema-common-jdbc". Pointing to [Virtual Schema Common Module for JDBC-based Data Access](https://github.com/exasol/virtual-schema-common-jdbc/blob/main/README.md#virtual-schema-common-module-for-jdbc-based-data-access) in Oracle SQL Dialect User Guide (**and the others** ...) is not convenient for a user, but that's what we should start from, I'd say.

**Comment by ckunki** [comment]
Hello @allipatev and @redcatbear please have a look at Oracle SQL Dialect User Guide, section [Creating a Virtual Schema](https://github.com/exasol/oracle-virtual-schema/blob/main/doc/user_guide/oracle_user_guide.md#creating-a-virtual-schema), containing a link to [Adapter Properties for JDBC-Based Virtual Schemas](https://github.com/exasol/virtual-schema-common-jdbc#adapter-properties-for-jdbc-based-virtual-schemas).

![image](https://user-images.githubusercontent.com/81821845/225530233-88c41ccf-7cb5-4c74-9ccd-77cac5dfe134.png)

Do you think this is sufficient or should we explicitly mention property `IMPORT_DATA_TYPES ` here?

**Comment by allipatev** [comment]
Hi @ckunki .
Looks good!

**Comment by ckunki** [comment]
Thanks for your answer @allipatev I will close the current ticket then.
