### ISSUE TITLE
Some improvements to oracle_user_guide.md

### ISSUE THREAD

**Issue by allipatev** [exasol/oracle-virtual-schema#7]
1. Typo: "indented" -> "intended"
2. MySQL is mentioned. May be Oracle was meant here?
3. Comment "Casted to VARCHAR to prevent a loss of precision." for the LONG data type might be misleading, as LONG in Oracle is character data type: https://docs.oracle.com/database/121/SQLRF/sql_elements001.htm#SQLRF30020

**Comment by AnastasiiaSergienko** [comment]
Thank you for reporting, @allipatev!
The fixes are merged.
